### ISSUE TITLE
Optionally generate a Copyright file

### ISSUE THREAD

**Issue by Ay1000** [enovationgroup/copyright-license-manager#9]
Hi,

Nice and handy tool..

It would be nice to have the same copyright information (maybe additionally the projectname) also in a file specified in the copyright.yaml. 

something like (see outputFile proposal):

```
source:
  - py
  - java
  - cs
  - ts
include:
  - "src/**/*"
exclude:
  - "**/*.min.js"
legal:
  - inception: 2014
    name: Enovation Group B.V.
    locality: Capelle aan den IJssel
    country: NL
format: "Copyright (c) {inception} - {year} [{name} - {locality} - {country}]"
license:
  enabled: true
  external: false
  content: All rights reserved.

outputFile: 
  enabled: true
  file: ./yyy/copyright.txt
  projectname: XXX
```

**Comment by eedzjee** [comment]
Hi @Ay1000,

I don't know if the tool is meant for this purpose. The original idea was to update copyright statements in source code in the right format. This takes away the hassle of changing a lot of files. Adding such a 'special' feature to just update one file seems a bit overkill? Why not change that file as well when the copyright changes?

I can imagine that it could come in handy for updating the year every time or when the legal entity changes, so all copyright and license data comes from the same place.

A way to handle this, is to implement a 'txt' or even a 'copyright.txt' source and handle that in the generator. You can then create a copyright.txt file in your project with your project's name in it and this tool will add the statement to it.

copyright.txt before
```
My Project
```

copyright.txt after
```
Copyright (c) 2014 - 2025 [{name} - {locality} - {country}]
My Project
```

copyright.yml:
```
source:
  - cs
  - copyright.txt
include:
  - "src/**/*"
  - "copyright.txt"
legal:
  - inception: 2014
    name: Enovation Group B.V.
    locality: Capelle aan den IJssel
    country: NL
format: "Copyright (c) {inception} - {year} [{name} - {locality} - {country}]"
license:
  enabled: true
  external: false
  content: All rights reserved
```

Do you have a suggestion of an example output copyright.txt file that it needs to produce? Or is there a standard/convention on the contents?
